/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import static hotelcalifornia.HotelCalifornia.espera;
import java.awt.Color;
import java.time.LocalDate;
import static java.time.temporal.ChronoUnit.DAYS;
import java.util.ArrayList;
import static vistas.Calendario.fechaSeleccionada;
import static vistas.Calendario.jlFecha;
import static vistas.Calendario.seleccionarFecha;

/**
 *
 * @author SANTIAGONB
 */
public class CuadroFecha extends javax.swing.JPanel {

    private boolean disponible;
    private int dia;
    private int mes;
    private int anio;
    private static LocalDate fecha;
    private Color gris;
    private Color azul;

    /**
     * Creates new form CuadroFecha1
     */
    public CuadroFecha(LocalDate f, boolean disponible) {
        setLayout(null);
        this.fecha = f;
        this.disponible = disponible;
        dia = fecha.getDayOfMonth();
        mes = fecha.getMonthValue();
        anio = fecha.getYear();
        setBounds(0, 0, 60, 40);
        initComponents();
        numero.setText(dia + "");
        gris = new Color(245, 245, 245);
        azul = new Color(0, 70, 250);
        validar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        numero = new javax.swing.JLabel();

        numero.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        numero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numero.setText("N");
        numero.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        numero.setMaximumSize(new java.awt.Dimension(100, 100));
        numero.setMinimumSize(new java.awt.Dimension(50, 30));
        numero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                numeroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                numeroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                numeroMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void numeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numeroMouseClicked
        if (disponible) {
            LocalDate fecha = LocalDate.of(anio, mes, dia);
            seleccionarFecha(fecha);
        }
    }//GEN-LAST:event_numeroMouseClicked

    private void numeroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numeroMouseEntered
        numero.setText(dia+"");
        if (disponible) {
            cambiarFondo(azul);
        }
    }//GEN-LAST:event_numeroMouseEntered

    private void numeroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numeroMouseExited
        if (disponible) {
            cambiarFondo(gris);
        }
    }//GEN-LAST:event_numeroMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel numero;
    // End of variables declaration//GEN-END:variables
    private void validar() {
        if (disponible) {
            numero.setForeground(Color.black);
            cambiarFondo(gris);
        } else {
            numero.setForeground(Color.red);
            cambiarFondo(Color.LIGHT_GRAY);
        }
    }

    public boolean isDisponible() {
        return disponible;
    }

    public void setDisponible(boolean disponible) {
        this.disponible = disponible;
    }

    public void cambiarFondo(Color fondo) {
        setBackground(fondo);
    }

}
