/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import accesoADatos.HabitacionData;
import accesoADatos.HuespedData;
import accesoADatos.ReservaData;
import accesoADatos.TipoHabData;
import entidades.Habitacion;
import entidades.Huesped;
import entidades.Reserva;
import entidades.TipoHabitacion;
import java.time.LocalDate;
import java.time.ZoneId;
import static java.time.temporal.ChronoUnit.DAYS;
import java.util.Date;
import java.util.List;
import java.util.TreeSet;
import javax.swing.JOptionPane;
import static vistas.VistaPrincipal.login;
import static vistas.VistaPrincipal.huespedActivo;
import static vistas.VistaPrincipal.mostrarVista;
import static vistas.VistaPrincipal.personal;

/**
 *
 * @author SANTIAGONB
 */
public class ReservarHabitacion extends javax.swing.JInternalFrame {

    /**
     * Creates new form ReservarHabitacion aaaaaa
     */
    HuespedData huData;
    HabitacionData habData;
    TipoHabData tipoData;
    ReservaData resData;
    double precioFinal;

    public ReservarHabitacion() {
        
        huData = new HuespedData();
        habData = new HabitacionData();
        tipoData = new TipoHabData();
        resData = new ReservaData();
        precioFinal = 0;
        
        initComponents();
        
        fechasMinMax();
        armarComboHuesped();
        jdateFechaIn.setDate(Date.from(LocalDate.now().atStartOfDay(ZoneId.systemDefault()).toInstant()));
        jdateFechaOut.setDate(Date.from(LocalDate.now().plusDays(1).atStartOfDay(ZoneId.systemDefault()).toInstant()));
        armarComboPiso();
        armarComboTipo();
        armarComboCant();
        armarComboHabitacion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jbReservar = new javax.swing.JButton();
        jlPrecioTxt = new javax.swing.JLabel();
        jPanel = new javax.swing.JPanel();
        jlHueped = new javax.swing.JLabel();
        jtHuesped = new javax.swing.JTextField();
        jcbHuesped = new javax.swing.JComboBox<>();
        jbIniciar = new javax.swing.JButton();
        jlBuscar = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jlHabitación = new javax.swing.JLabel();
        jcbTipoHab = new javax.swing.JComboBox<>();
        jlPiso = new javax.swing.JLabel();
        jcbPiso = new javax.swing.JComboBox<>();
        jlFechaIn = new javax.swing.JLabel();
        jlFechaOut = new javax.swing.JLabel();
        jdateFechaOut = new com.toedter.calendar.JDateChooser();
        jdateFechaIn = new com.toedter.calendar.JDateChooser();
        jlTipoHab = new javax.swing.JLabel();
        jlHab = new javax.swing.JLabel();
        jcbHab = new javax.swing.JComboBox<>();
        jlNochesTxt = new javax.swing.JLabel();
        jlNochesN = new javax.swing.JLabel();
        jlPrecioXNocheTxt = new javax.swing.JLabel();
        jlPrecioXNocheN = new javax.swing.JLabel();
        jlCant = new javax.swing.JLabel();
        jcbCant = new javax.swing.JComboBox<>();
        jbSalir = new javax.swing.JButton();

        setTitle("Reservar habitación");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/hc_logo.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Reservar Habitación");

        jbReservar.setText("Reservar");
        jbReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbReservarActionPerformed(evt);
            }
        });

        jlPrecioTxt.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlPrecioTxt.setText("Precio Total: $ 0");

        jPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jlHueped.setText("Huesped");

        jtHuesped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtHuespedActionPerformed(evt);
            }
        });
        jtHuesped.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtHuespedKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtHuespedKeyTyped(evt);
            }
        });

        jcbHuesped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbHuespedActionPerformed(evt);
            }
        });

        jbIniciar.setText("Iniciar sesión");
        jbIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbIniciarActionPerformed(evt);
            }
        });

        jlBuscar.setText("Buscar huesped por dni o nombre");

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jlHueped)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addComponent(jlBuscar)
                                .addGap(0, 262, Short.MAX_VALUE))
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jbIniciar))
                            .addComponent(jtHuesped)
                            .addComponent(jcbHuesped, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(24, 24, 24))))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jlHueped)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jlBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbIniciar)
                .addGap(10, 10, 10))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jlHabitación.setText("Habitación");

        jcbTipoHab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTipoHabActionPerformed(evt);
            }
        });

        jlPiso.setText("Piso: ");

        jcbPiso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbPisoActionPerformed(evt);
            }
        });

        jlFechaIn.setText("Fecha de ingreso:");

        jlFechaOut.setText("Fecha de salida:");

        jdateFechaOut.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jdateFechaOutPropertyChange(evt);
            }
        });

        jdateFechaIn.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jdateFechaInPropertyChange(evt);
            }
        });

        jlTipoHab.setText("Tipo de habitación:");

        jlHab.setText("Habitacion N°:");

        jlNochesTxt.setText("Noches:");

        jlNochesN.setText("0");

        jlPrecioXNocheTxt.setText("Precio por Noche: $");

        jlPrecioXNocheN.setText("0");

        jlCant.setText("Cant de huespedes:");

        jcbCant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbCantActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlHabitación)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jlHab)
                                    .addGap(51, 51, 51)
                                    .addComponent(jcbHab, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(jlPrecioXNocheTxt)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jlPrecioXNocheN))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(1, 1, 1)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jlFechaIn)
                                        .addComponent(jlFechaOut))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jlNochesTxt)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jlNochesN)
                                    .addGap(9, 9, 9))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jlPiso)
                                    .addGap(99, 99, 99)
                                    .addComponent(jcbPiso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jlTipoHab, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jlCant)
                                .addGap(17, 17, 17)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jcbCant, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jdateFechaIn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                            .addComponent(jdateFechaOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbTipoHab, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(27, 27, 27))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jlHabitación)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdateFechaIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlFechaIn, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlFechaOut)
                    .addComponent(jdateFechaOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlNochesN, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlNochesTxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbPiso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlPiso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbTipoHab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlTipoHab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbCant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCant))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbHab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlHab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlPrecioXNocheN, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlPrecioXNocheTxt))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel1)
                            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jbSalir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlPrecioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbReservar)))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbReservar)
                    .addComponent(jlPrecioTxt)
                    .addComponent(jbSalir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbReservarActionPerformed
        reservar();
    }//GEN-LAST:event_jbReservarActionPerformed

    private void jtHuespedKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtHuespedKeyTyped
        //armarComboHuesped();        
    }//GEN-LAST:event_jtHuespedKeyTyped

    private void jtHuespedKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtHuespedKeyReleased
        armarComboHuesped();
    }//GEN-LAST:event_jtHuespedKeyReleased

    private void jdateFechaInPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jdateFechaInPropertyChange
        jlNochesN.setText(calcularNoches() + "");
        jlPrecioTxt.setText("PRECIO FINAL: $"+calcularPrecio());
    }//GEN-LAST:event_jdateFechaInPropertyChange

    private void jdateFechaOutPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jdateFechaOutPropertyChange
        jlNochesN.setText(calcularNoches() + "");
        jlPrecioTxt.setText("PRECIO FINAL: $"+calcularPrecio());
    }//GEN-LAST:event_jdateFechaOutPropertyChange

    private void jcbTipoHabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTipoHabActionPerformed
        jlPrecioTxt.setText("PRECIO FINAL: $"+calcularPrecio());
        armarComboHabitacion();
        armarComboCant();
    }//GEN-LAST:event_jcbTipoHabActionPerformed

    private void jcbPisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbPisoActionPerformed
        armarComboHabitacion();
    }//GEN-LAST:event_jcbPisoActionPerformed

    private void jcbCantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbCantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbCantActionPerformed

    private void jcbHuespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbHuespedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbHuespedActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jbIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbIniciarActionPerformed
        Login ingresar = new Login(personal);
        mostrarVista(ingresar);
    }//GEN-LAST:event_jbIniciarActionPerformed

    private void jtHuespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtHuespedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtHuespedActionPerformed

    private void comboHuespedes() {
        List huespedes = huData.listarHuespedes();
        for (Object hu : huespedes) {
            Huesped huesped = (Huesped) hu;
            jcbHuesped.addItem(huesped);
        }

    }

    private void buscarHuesped() {

        List huespedes = huData.listarHuespedes();

        String texto = jtHuesped.getText().toLowerCase();

        for (Object hu : huespedes) {

            Huesped huesped = (Huesped) hu;

            String nombre = huesped.getNombre().toLowerCase();
            String apellido = huesped.getApellido().toLowerCase();
            String dni = huesped.getDni() + "";
            String nomAp = nombre + " " + apellido;
            String apNom = apellido + " " + nombre;

            boolean nombreMatch = nombre.startsWith(texto);
            boolean apellidoMatch = apellido.startsWith(texto);
            boolean dniMatch = dni.startsWith(texto);
            boolean nomApMatch = nomAp.startsWith(texto);
            boolean apNomMatch = apNom.startsWith(texto);

            if (nombreMatch || apellidoMatch || dniMatch || nomApMatch || apNomMatch) {
                jcbHuesped.addItem(huesped);
            }
        }
    }

    private void armarComboHuesped() {
        jcbHuesped.removeAllItems();
        
        if (login){
            if (personal){
                if (jtHuesped.getText().isEmpty()) {
                    comboHuespedes();
                } else {
                    buscarHuesped();
                }
            } else {
                jcbHuesped.addItem(huespedActivo);
                jtHuesped.setEditable(false);
            }
        } else {
            jtHuesped.setEditable(false);
            jcbHuesped.setEnabled(false);
        }
        
    }

    private void armarComboPiso() {
        List habitaciones = habData.listarHabitacionesTodas();
        TreeSet<Integer> pisos = new TreeSet<>();
        for (Object hab : habitaciones) {
            Habitacion habitacion = (Habitacion) hab;
            int piso = habitacion.getPiso();
            pisos.add(piso);
        }
        for (int piso : pisos) {
            jcbPiso.addItem(piso);
        }
    }

    private void armarComboCant() {
        jcbCant.removeAllItems();
        TipoHabitacion tipo = (TipoHabitacion) jcbTipoHab.getSelectedItem();
        int max = tipo.getCantPersonas();
        for (int i = 1; i <= max; i++) {
            jcbCant.addItem(i);
        }
    }

    private void armarComboTipo() {
        List tipos = tipoData.listarTipos();
        for (Object t : tipos) {
            TipoHabitacion tipo = (TipoHabitacion) t;
            jcbTipoHab.addItem(tipo);
        }
    }

    private void armarComboHabitacion() {
        jcbHab.removeAllItems();
        try {
            int piso = (int) jcbPiso.getSelectedItem();
            TipoHabitacion tipo = (TipoHabitacion) jcbTipoHab.getSelectedItem();
            List habitaciones = habData.listarHabitacionesXPisoYTipo(piso, tipo);
            for (Object hab : habitaciones) {
                Habitacion habitacion = (Habitacion) hab;
                jcbHab.addItem(habitacion);
            }
        } catch (NullPointerException np) {

        }
    }

    private int calcularNoches() {
        try {
            LocalDate fechaIn = jdateFechaIn.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            LocalDate fechaOut = jdateFechaOut.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            int noches = (int) DAYS.between(fechaIn, fechaOut);
            if (noches > 0) {
                return noches;
            } else {
                return 0;
            }
        } catch (NullPointerException np) {
            return 0;
        }
    }

    private double calcularPrecio() {
        try {
            TipoHabitacion tipo = (TipoHabitacion) jcbTipoHab.getSelectedItem();
            double precioXNoche = tipo.getPrecioxNoche();
            jlPrecioXNocheN.setText(precioXNoche + "");
            precioFinal = precioXNoche * calcularNoches();
        } catch (NullPointerException np) {
            jlPrecioXNocheN.setText("0");
        }
        return precioFinal;
    }

    private void reservar() {
        if (login) {
            Reserva reserva = new Reserva();
            reserva.setFechaCheckIn(jdateFechaIn.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
            reserva.setFechaCheckOut(jdateFechaOut.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
            reserva.setEstado(true);
            reserva.setHabitacion((Habitacion) jcbHab.getSelectedItem());
            reserva.setHuesped((Huesped) jcbHuesped.getSelectedItem());
            reserva.setPrecioTotal(precioFinal);
            reserva.setCantPersonas((int) jcbCant.getSelectedItem());
            resData.agregarReserva(reserva);
        } else {
            JOptionPane.showMessageDialog(null, "Debe iniciar sesión para reservar");
        }
    }
    
    private void coloresFechas(Habitacion habitacion){
            
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbIniciar;
    private javax.swing.JButton jbReservar;
    private javax.swing.JButton jbSalir;
    private javax.swing.JComboBox<Integer> jcbCant;
    private javax.swing.JComboBox<Habitacion> jcbHab;
    private javax.swing.JComboBox<Huesped> jcbHuesped;
    private javax.swing.JComboBox<Integer> jcbPiso;
    private javax.swing.JComboBox<TipoHabitacion> jcbTipoHab;
    private com.toedter.calendar.JDateChooser jdateFechaIn;
    private com.toedter.calendar.JDateChooser jdateFechaOut;
    private javax.swing.JLabel jlBuscar;
    private javax.swing.JLabel jlCant;
    private javax.swing.JLabel jlFechaIn;
    private javax.swing.JLabel jlFechaOut;
    private javax.swing.JLabel jlHab;
    private javax.swing.JLabel jlHabitación;
    private javax.swing.JLabel jlHueped;
    private javax.swing.JLabel jlNochesN;
    private javax.swing.JLabel jlNochesTxt;
    private javax.swing.JLabel jlPiso;
    private javax.swing.JLabel jlPrecioTxt;
    private javax.swing.JLabel jlPrecioXNocheN;
    private javax.swing.JLabel jlPrecioXNocheTxt;
    private javax.swing.JLabel jlTipoHab;
    private javax.swing.JTextField jtHuesped;
    // End of variables declaration//GEN-END:variables

    private void fechasMinMax(){
        jdateFechaIn.setMinSelectableDate(Date.from(LocalDate.now().atStartOfDay(ZoneId.systemDefault()).toInstant()));
        jdateFechaOut.setMinSelectableDate(Date.from(LocalDate.now().plusDays(1).atStartOfDay(ZoneId.systemDefault()).toInstant()));
        jdateFechaIn.setMaxSelectableDate(Date.from(LocalDate.now().plusDays(364).atStartOfDay(ZoneId.systemDefault()).toInstant()));
        jdateFechaOut.setMaxSelectableDate(Date.from(LocalDate.now().plusDays(365).atStartOfDay(ZoneId.systemDefault()).toInstant()));
    }

}
