/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import accesoADatos.HabitacionData;
import accesoADatos.HuespedData;
import accesoADatos.ReservaData;
import accesoADatos.TipoHabData;
import entidades.Habitacion;
import entidades.Huesped;
import entidades.Reserva;
import entidades.TipoHabitacion;
import java.awt.Image;
import java.time.LocalDate;
import static java.time.temporal.ChronoUnit.DAYS;
import java.util.List;
import java.util.TreeSet;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static vistas.VistaPrincipal.huespedActivo;
import static vistas.VistaPrincipal.login;
import static vistas.VistaPrincipal.mostrarVista;
import static vistas.VistaPrincipal.personal;
import static vistas.VistaPrincipal.personalActivo;

/**
 *
 * @author SANTIAGONB
 */
public class ReservarHabitacion extends javax.swing.JInternalFrame {

    /**
     * Creates new form ReservarHabitacion aaaaaa
     */
    private HuespedData huData;
    private HabitacionData habData;
    private TipoHabData tipoData;
    private double precioFinal;

    private static ReservaData resData;
    public static Habitacion habitacionActiva;
    public static LocalDate fechaIn;
    public static LocalDate fechaOut;
    public static JFrame elegir;

    public ReservarHabitacion() {

        huData = new HuespedData();
        habData = new HabitacionData();
        tipoData = new TipoHabData();
        resData = new ReservaData();
        precioFinal = 0;

        habitacionActiva = null;

        initComponents();

        armarInicioSesion();
        armarComboHuesped();
        armarComboPiso();
        armarComboTipo();
        armarComboCant();
        armarComboHabitacion();
        colocarImagen();
        setLayout(null);
        setSize(1000, 540);
        jPanelCapas.setLayout(null);
        jPanelCapas.setBounds(0, 0, 1000, 520);
        jlTitulo.setBounds(0, 0, 580, 30);
        jPanelHuesped.setBounds(30, 30, 520, 175);
        jPanelHabitacion.setBounds(30, 210, 520, 275);

        jlImagen.setBounds(560, 30, 400, 400);
        jPanelFinal.setBounds(560, 435, 400, 50);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCapas = new javax.swing.JLayeredPane();
        jlTitulo = new javax.swing.JLabel();
        jPanelHuesped = new javax.swing.JPanel();
        jlHueped = new javax.swing.JLabel();
        jtHuesped = new javax.swing.JTextField();
        jcbHuesped = new javax.swing.JComboBox<>();
        jbIniciarHuesped = new javax.swing.JButton();
        jlBuscar = new javax.swing.JLabel();
        jbIniciarPersonal = new javax.swing.JButton();
        jbCerrarSesion = new javax.swing.JButton();
        jPanelHabitacion = new javax.swing.JPanel();
        jlHabitación = new javax.swing.JLabel();
        jcbTipoHab = new javax.swing.JComboBox<>();
        jlPiso = new javax.swing.JLabel();
        jcbPiso = new javax.swing.JComboBox<>();
        jlFechaIn = new javax.swing.JLabel();
        jlFechaOut = new javax.swing.JLabel();
        jlTipoHab = new javax.swing.JLabel();
        jlHab = new javax.swing.JLabel();
        jcbHab = new javax.swing.JComboBox<>();
        jlNoches = new javax.swing.JLabel();
        jlPrecioXNocheTxt = new javax.swing.JLabel();
        jlPrecioXNocheN = new javax.swing.JLabel();
        jlCant = new javax.swing.JLabel();
        jcbCant = new javax.swing.JComboBox<>();
        jlMostrarFechaIn = new javax.swing.JLabel();
        jlMostrarFechaOut = new javax.swing.JLabel();
        jbElegirIn = new javax.swing.JButton();
        jbElegirOut = new javax.swing.JButton();
        jPanelFinal = new javax.swing.JPanel();
        jbSalir = new javax.swing.JButton();
        jbReservar = new javax.swing.JButton();
        jlPrecioTxt = new javax.swing.JLabel();
        jlImagen = new javax.swing.JLabel();

        setTitle("Reservar habitación");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/hc_logo.png"))); // NOI18N

        jPanelCapas.setPreferredSize(new java.awt.Dimension(560, 600));

        jlTitulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTitulo.setText("Reservar Habitación");

        jPanelHuesped.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jlHueped.setText("Huesped");

        jtHuesped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtHuespedActionPerformed(evt);
            }
        });
        jtHuesped.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtHuespedKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtHuespedKeyTyped(evt);
            }
        });

        jcbHuesped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbHuespedActionPerformed(evt);
            }
        });

        jbIniciarHuesped.setText("Iniciar sesión como huesped");
        jbIniciarHuesped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbIniciarHuespedActionPerformed(evt);
            }
        });

        jlBuscar.setText("Buscar huesped por dni o nombre");

        jbIniciarPersonal.setText("Iniciar sesión como personal del hotel");
        jbIniciarPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbIniciarPersonalActionPerformed(evt);
            }
        });

        jbCerrarSesion.setText("Cerrar sesión");
        jbCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCerrarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelHuespedLayout = new javax.swing.GroupLayout(jPanelHuesped);
        jPanelHuesped.setLayout(jPanelHuespedLayout);
        jPanelHuespedLayout.setHorizontalGroup(
            jPanelHuespedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHuespedLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanelHuespedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelHuespedLayout.createSequentialGroup()
                        .addGroup(jPanelHuespedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlBuscar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbHuesped, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtHuesped, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlHueped, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(60, Short.MAX_VALUE))
                    .addGroup(jPanelHuespedLayout.createSequentialGroup()
                        .addGroup(jPanelHuespedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelHuespedLayout.createSequentialGroup()
                                .addComponent(jbIniciarPersonal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbIniciarHuesped)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanelHuespedLayout.setVerticalGroup(
            jPanelHuespedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHuespedLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jlHueped)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelHuespedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbIniciarHuesped)
                    .addComponent(jbIniciarPersonal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbCerrarSesion)
                .addGap(8, 8, 8))
        );

        jPanelHabitacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jlHabitación.setText("Habitación");

        jcbTipoHab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTipoHabActionPerformed(evt);
            }
        });

        jlPiso.setText("Piso: ");

        jcbPiso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbPisoActionPerformed(evt);
            }
        });

        jlFechaIn.setText("Desde:");

        jlFechaOut.setText("Hasta:");

        jlTipoHab.setText("Tipo de habitación:");

        jlHab.setText("Habitacion N°:");

        jcbHab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbHabActionPerformed(evt);
            }
        });

        jlNoches.setText("Noches: 0 - (Salida: )");

        jlPrecioXNocheTxt.setText("Precio por Noche: $");

        jlPrecioXNocheN.setText("0");

        jlCant.setText("Cant de huespedes:");

        jcbCant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbCantActionPerformed(evt);
            }
        });

        jlMostrarFechaIn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlMostrarFechaIn.setText("----");
        jlMostrarFechaIn.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jlMostrarFechaInPropertyChange(evt);
            }
        });

        jlMostrarFechaOut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlMostrarFechaOut.setText("----");
        jlMostrarFechaOut.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jlMostrarFechaOutPropertyChange(evt);
            }
        });

        jbElegirIn.setText("Elegir");
        jbElegirIn.setPreferredSize(new java.awt.Dimension(70, 32));
        jbElegirIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbElegirInActionPerformed(evt);
            }
        });

        jbElegirOut.setText("Elegir");
        jbElegirOut.setPreferredSize(new java.awt.Dimension(70, 32));
        jbElegirOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbElegirOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelHabitacionLayout = new javax.swing.GroupLayout(jPanelHabitacion);
        jPanelHabitacion.setLayout(jPanelHabitacionLayout);
        jPanelHabitacionLayout.setHorizontalGroup(
            jPanelHabitacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHabitacionLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanelHabitacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlNoches)
                    .addGroup(jPanelHabitacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanelHabitacionLayout.createSequentialGroup()
                            .addComponent(jlFechaIn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlMostrarFechaIn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jbElegirIn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(33, 33, 33)
                            .addComponent(jlFechaOut, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jlMostrarFechaOut, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jbElegirOut, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(8, 8, 8))
                        .addGroup(jPanelHabitacionLayout.createSequentialGroup()
                            .addGroup(jPanelHabitacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jlHab, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jlCant, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jlTipoHab, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jlPiso, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jlHabitación, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(42, 42, 42)
                            .addGroup(jPanelHabitacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jcbPiso, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jcbTipoHab, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jcbCant, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jcbHab, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanelHabitacionLayout.createSequentialGroup()
                                    .addComponent(jlPrecioXNocheTxt)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jlPrecioXNocheN))))))
                .addGap(30, 30, 30))
        );
        jPanelHabitacionLayout.setVerticalGroup(
            jPanelHabitacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHabitacionLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jlHabitación)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelHabitacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jbElegirIn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlFechaIn)
                    .addComponent(jlMostrarFechaIn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlMostrarFechaOut, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbElegirOut, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlFechaOut))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlNoches)
                .addGap(22, 22, 22)
                .addGroup(jPanelHabitacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbPiso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlPiso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelHabitacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbTipoHab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlTipoHab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelHabitacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbCant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCant))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelHabitacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbHab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlHab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelHabitacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlPrecioXNocheN, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlPrecioXNocheTxt))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanelFinal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        jbReservar.setText("Reservar");
        jbReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbReservarActionPerformed(evt);
            }
        });

        jlPrecioTxt.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlPrecioTxt.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlPrecioTxt.setText("Precio Total: $ 0");

        javax.swing.GroupLayout jPanelFinalLayout = new javax.swing.GroupLayout(jPanelFinal);
        jPanelFinal.setLayout(jPanelFinalLayout);
        jPanelFinalLayout.setHorizontalGroup(
            jPanelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFinalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlPrecioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbReservar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );
        jPanelFinalLayout.setVerticalGroup(
            jPanelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFinalLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbReservar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlPrecioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jlImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlImagen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanelCapas.setLayer(jlTitulo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jPanelCapas.setLayer(jPanelHuesped, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jPanelCapas.setLayer(jPanelHabitacion, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jPanelCapas.setLayer(jPanelFinal, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jPanelCapas.setLayer(jlImagen, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jPanelCapasLayout = new javax.swing.GroupLayout(jPanelCapas);
        jPanelCapas.setLayout(jPanelCapasLayout);
        jPanelCapasLayout.setHorizontalGroup(
            jPanelCapasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCapasLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanelCapasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jPanelHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCapasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(73, 73, 73))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCapasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlTitulo)
                .addGap(459, 459, 459))
        );
        jPanelCapasLayout.setVerticalGroup(
            jPanelCapasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCapasLayout.createSequentialGroup()
                .addComponent(jlTitulo)
                .addGap(12, 12, 12)
                .addGroup(jPanelCapasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCapasLayout.createSequentialGroup()
                        .addComponent(jPanelHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCapasLayout.createSequentialGroup()
                        .addComponent(jlImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanelFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCapas, javax.swing.GroupLayout.DEFAULT_SIZE, 1140, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCapas, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbReservarActionPerformed
        reservar();
    }//GEN-LAST:event_jbReservarActionPerformed

    private void jtHuespedKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtHuespedKeyTyped

    }//GEN-LAST:event_jtHuespedKeyTyped

    private void jtHuespedKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtHuespedKeyReleased
        armarComboHuesped();
    }//GEN-LAST:event_jtHuespedKeyReleased

    private void jcbTipoHabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTipoHabActionPerformed
        armarComboHabitacion();
        armarComboCant();
        calcularPrecio();
    }//GEN-LAST:event_jcbTipoHabActionPerformed

    private void jcbPisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbPisoActionPerformed
        armarComboHabitacion();
    }//GEN-LAST:event_jcbPisoActionPerformed

    private void jcbCantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbCantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbCantActionPerformed

    private void jcbHuespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbHuespedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbHuespedActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jbIniciarHuespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbIniciarHuespedActionPerformed
        personal = false;
        Login ingresar = new Login(personal);
        mostrarVista(ingresar);
    }//GEN-LAST:event_jbIniciarHuespedActionPerformed

    private void jtHuespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtHuespedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtHuespedActionPerformed

    private void jcbHabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbHabActionPerformed
        habitacionActiva = (Habitacion) jcbHab.getSelectedItem();
        colocarImagen();
    }//GEN-LAST:event_jcbHabActionPerformed

    private void jbElegirInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbElegirInActionPerformed
        elegir(true);
    }//GEN-LAST:event_jbElegirInActionPerformed

    private void jbElegirOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbElegirOutActionPerformed
        elegir(false);
    }//GEN-LAST:event_jbElegirOutActionPerformed

    private void jlMostrarFechaInPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jlMostrarFechaInPropertyChange
        calcularPrecio();
    }//GEN-LAST:event_jlMostrarFechaInPropertyChange

    private void jlMostrarFechaOutPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jlMostrarFechaOutPropertyChange
        calcularPrecio();
    }//GEN-LAST:event_jlMostrarFechaOutPropertyChange

    private void jbIniciarPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbIniciarPersonalActionPerformed
        personal = true;
        Login ingresar = new Login(personal);
        mostrarVista(ingresar);
    }//GEN-LAST:event_jbIniciarPersonalActionPerformed

    private void jbCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCerrarSesionActionPerformed
        login = false;
        personal = false;
        personalActivo = null;
        huespedActivo = null;
        dispose();
        mostrarVista(new ReservarHabitacion());
    }//GEN-LAST:event_jbCerrarSesionActionPerformed

    private void comboHuespedes() {
        List huespedes = huData.listarHuespedes();
        for (Object hu : huespedes) {
            Huesped huesped = (Huesped) hu;
            jcbHuesped.addItem(huesped);
        }
    }

    private void buscarHuesped() {

        List huespedes = huData.listarHuespedes();

        String texto = jtHuesped.getText().toLowerCase();

        for (Object hu : huespedes) {

            Huesped huesped = (Huesped) hu;

            String nombre = huesped.getNombre().toLowerCase();
            String apellido = huesped.getApellido().toLowerCase();
            String dni = huesped.getDni() + "";
            String nomAp = nombre + " " + apellido;
            String apNom = apellido + " " + nombre;

            boolean nombreMatch = nombre.startsWith(texto);
            boolean apellidoMatch = apellido.startsWith(texto);
            boolean dniMatch = dni.startsWith(texto);
            boolean nomApMatch = nomAp.startsWith(texto);
            boolean apNomMatch = apNom.startsWith(texto);

            if (nombreMatch || apellidoMatch || dniMatch || nomApMatch || apNomMatch) {
                jcbHuesped.addItem(huesped);
            }
        }
    }

    private void armarComboHuesped() {
        jcbHuesped.removeAllItems();

        if (login) {
            if (personal) {
                if (jtHuesped.getText().isEmpty()) {
                    comboHuespedes();
                } else {
                    buscarHuesped();
                }
            } else {
                jcbHuesped.addItem(huespedActivo);
                jtHuesped.setEditable(false);
            }
        } else {
            jtHuesped.setEditable(false);
            jcbHuesped.setEnabled(false);
        }

    }

    private void armarComboPiso() {
        List habitaciones = habData.listarHabitacionesTodas();
        TreeSet<Integer> pisos = new TreeSet<>();
        for (Object hab : habitaciones) {
            Habitacion habitacion = (Habitacion) hab;
            int piso = habitacion.getPiso();
            pisos.add(piso);
        }
        for (int piso : pisos) {
            jcbPiso.addItem(piso);
        }
    }

    private void armarComboCant() {
        jcbCant.removeAllItems();
        TipoHabitacion tipo = (TipoHabitacion) jcbTipoHab.getSelectedItem();
        int max = tipo.getCantPersonas();
        for (int i = 1; i <= max; i++) {
            jcbCant.addItem(i);
        }
    }

    private void armarComboTipo() {
        List tipos = tipoData.listarTipos();
        for (Object t : tipos) {
            TipoHabitacion tipo = (TipoHabitacion) t;
            jcbTipoHab.addItem(tipo);
        }
    }

    private void armarComboHabitacion() {
        jcbHab.removeAllItems();
        try {
            int piso = (int) jcbPiso.getSelectedItem();
            TipoHabitacion tipo = (TipoHabitacion) jcbTipoHab.getSelectedItem();
            List habitaciones = habData.listarHabitacionesXPisoYTipo(piso, tipo);
            for (Object hab : habitaciones) {
                Habitacion habitacion = (Habitacion) hab;
                jcbHab.addItem(habitacion);
            }
            habitacionActiva = (Habitacion) jcbHab.getSelectedItem();
        } catch (NullPointerException np) {

        }
    }

    private int calcularNoches() {
        int noches = 0;
        try {
            noches = (int) DAYS.between(fechaIn, fechaOut) + 1;
            if (noches <= 0) {
                noches = 0;
            }
        } catch (NullPointerException np) {

        }
        jlNoches.setText("Noches: " + noches + " (Salida: " + fechaOut.plusDays(1) + " a las 10:00 am)");
        return noches;
    }

    public double calcularPrecio() {
        try {
            TipoHabitacion tipo = (TipoHabitacion) jcbTipoHab.getSelectedItem();
            double precioXNoche = tipo.getPrecioxNoche();
            jlPrecioXNocheN.setText(precioXNoche + "");
            precioFinal = precioXNoche * calcularNoches();
            jlPrecioTxt.setText("Precio final: $" + precioFinal);
        } catch (NullPointerException np) {

        }
        return precioFinal;
    }

    private void reservar() {
        if (login) {
            Reserva reserva = new Reserva();
            reserva.setFechaCheckIn(fechaIn);
            reserva.setFechaCheckOut(fechaOut);
            reserva.setEstado(true);
            reserva.setHabitacion((Habitacion) jcbHab.getSelectedItem());
            reserva.setHuesped((Huesped) jcbHuesped.getSelectedItem());
            reserva.setPrecioTotal(precioFinal);
            reserva.setCantPersonas((int) jcbCant.getSelectedItem());
            resData.agregarReserva(reserva);
            resData.actualizarDisponibilidad();
        } else {
            JOptionPane.showMessageDialog(null, "Debe iniciar sesión para reservar");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane jPanelCapas;
    private javax.swing.JPanel jPanelFinal;
    private javax.swing.JPanel jPanelHabitacion;
    private javax.swing.JPanel jPanelHuesped;
    private javax.swing.JButton jbCerrarSesion;
    private javax.swing.JButton jbElegirIn;
    private javax.swing.JButton jbElegirOut;
    private javax.swing.JButton jbIniciarHuesped;
    private javax.swing.JButton jbIniciarPersonal;
    private javax.swing.JButton jbReservar;
    private javax.swing.JButton jbSalir;
    private javax.swing.JComboBox<Integer> jcbCant;
    private javax.swing.JComboBox<Habitacion> jcbHab;
    private javax.swing.JComboBox<Huesped> jcbHuesped;
    private javax.swing.JComboBox<Integer> jcbPiso;
    private javax.swing.JComboBox<TipoHabitacion> jcbTipoHab;
    private javax.swing.JLabel jlBuscar;
    private javax.swing.JLabel jlCant;
    private javax.swing.JLabel jlFechaIn;
    private javax.swing.JLabel jlFechaOut;
    private javax.swing.JLabel jlHab;
    private javax.swing.JLabel jlHabitación;
    private javax.swing.JLabel jlHueped;
    private javax.swing.JLabel jlImagen;
    public static javax.swing.JLabel jlMostrarFechaIn;
    public static javax.swing.JLabel jlMostrarFechaOut;
    private javax.swing.JLabel jlNoches;
    private javax.swing.JLabel jlPiso;
    private javax.swing.JLabel jlPrecioTxt;
    private javax.swing.JLabel jlPrecioXNocheN;
    private javax.swing.JLabel jlPrecioXNocheTxt;
    private javax.swing.JLabel jlTipoHab;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JTextField jtHuesped;
    // End of variables declaration//GEN-END:variables

    private void elegir(boolean in) {

        if (jcbHab.getSelectedIndex() >= 0) {
            elegir = new JFrame();
            elegir.setSize(480, 400);
            elegir.setLocationRelativeTo(this);
            elegir.setUndecorated(true);
            elegir.setVisible(true);
            elegir.add(new Calendario(in));
        } else {
            JOptionPane.showMessageDialog(null, "Debe elegir una habitación");
        }

    }

    private void armarInicioSesion() {
        jbCerrarSesion.setVisible(login);
        jbIniciarPersonal.setVisible(!login);
        jbIniciarHuesped.setVisible(!login);
        jbSalir.setVisible(login);
    }

    private void colocarImagen() {
        try {
            ImageIcon imagen = habitacionActiva.getImagen().getImagen();
            int bImagen = imagen.getIconWidth();
            int hImagen = imagen.getIconHeight();
            int bLabel = 400;
            double rel = (double) bLabel / (double) bImagen;
            int hEscalado = (int) (hImagen * rel);
            ImageIcon imagenEscalada = new ImageIcon(imagen.getImage().getScaledInstance(bLabel, hEscalado, Image.SCALE_SMOOTH));
            jlImagen.setIcon(imagenEscalada);
            jlImagen.setText("");
        } catch (NullPointerException np) {
            jlImagen.setIcon(null);
            jlImagen.setText("Imagen no disponible");
        }
    }

}
