/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import accesoADatos.TipoHabData;

import entidades.Habitacion;
import entidades.TipoHabitacion;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author INTEL
 */
public class TipoHabitaciones extends javax.swing.JInternalFrame {

    /**
     * Creates new form TipoHabitaciones
     */
    public TipoHabitaciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtfIdTipoHab = new javax.swing.JTextField();
        jtfNombre = new javax.swing.JTextField();
        jtfCantPersonas = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtfCantCamas = new javax.swing.JTextField();
        jlTipoCama = new javax.swing.JLabel();
        jtfTipoCama = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtfPrecioxNoche = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jrbEstado = new javax.swing.JRadioButton();
        jbAgregar = new javax.swing.JButton();
        jbModificar = new javax.swing.JButton();
        jbNuevo = new javax.swing.JButton();
        jbDarAltaBaja = new javax.swing.JButton();
        jbBuscar = new javax.swing.JButton();
        jtfBuscar = new javax.swing.JTextField();
        jbSalir = new javax.swing.JButton();

        setTitle("Manejo de tipos de habitación");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/hc_logo.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Tipos de Habitación");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        jLabel2.setText("Id Tipo Habitación:");

        jLabel8.setText("Nombre:");

        jtfIdTipoHab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfIdTipoHabActionPerformed(evt);
            }
        });

        jtfNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNombreActionPerformed(evt);
            }
        });

        jLabel3.setText("Cantidad de personas:");

        jLabel4.setText("Cantidad de camas:");

        jlTipoCama.setText("Tipo de camas:");

        jtfTipoCama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfTipoCamaActionPerformed(evt);
            }
        });

        jLabel5.setText("Precio por noche:");

        jLabel6.setText("USD");

        jLabel9.setText("Estado:");

        jrbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbEstadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfNombre)
                            .addComponent(jtfIdTipoHab)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jlTipoCama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jrbEstado)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jtfPrecioxNoche, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addGap(20, 20, 20))
                            .addComponent(jtfTipoCama)
                            .addComponent(jtfCantCamas)
                            .addComponent(jtfCantPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(99, 99, 99))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfIdTipoHab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfCantPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfCantCamas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfTipoCama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlTipoCama, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtfPrecioxNoche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jrbEstado))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jbAgregar.setText("Agregar");
        jbAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarActionPerformed(evt);
            }
        });

        jbModificar.setText("Modificar");
        jbModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarActionPerformed(evt);
            }
        });

        jbNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/limpiar.png"))); // NOI18N
        jbNuevo.setToolTipText("Limpiar formulario");
        jbNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoActionPerformed(evt);
            }
        });

        jbDarAltaBaja.setText("Dar alta / baja");
        jbDarAltaBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDarAltaBajaActionPerformed(evt);
            }
        });

        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jtfBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfBuscarActionPerformed(evt);
            }
        });

        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jtfBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbBuscar)
                                .addGap(7, 7, 7))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbModificar)
                                .addGap(18, 18, 18)
                                .addComponent(jbDarAltaBaja)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbSalir)))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbBuscar)
                    .addComponent(jtfBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbDarAltaBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarActionPerformed

        jtfIdTipoHab.setEditable(true);
        jtfNombre.setEditable(true);
        jtfCantCamas.setEditable(true);
        jtfCantPersonas.setEditable(true);
        jtfPrecioxNoche.setEditable(true);
        jtfTipoCama.setEditable(true);
        jrbEstado.setEnabled(false);
        try {
            TipoHabData th = new TipoHabData();
            TipoHabitacion hb = new TipoHabitacion();
            int id = Integer.parseInt(jtfIdTipoHab.getText());
            hb.setIdTipoHab(id);
            hb.setIdTipoHab(Integer.parseInt(jtfIdTipoHab.getText()));
            hb.setNombre(jtfNombre.getText());
            hb.setCantPersonas(Integer.parseInt(jtfCantPersonas.getText()));
            hb.setCantCamas(Integer.parseInt(jtfCantCamas.getText()));
            hb.setTipoCamas(jtfTipoCama.getText());
            hb.setPrecioxNoche(Double.parseDouble(jtfPrecioxNoche.getText()));
            hb.setEstado(jrbEstado.isSelected());
            th.modificarTipo(hb);
            nuevo();

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "El Id ingresado debe ser un número");

        }
    }//GEN-LAST:event_jbModificarActionPerformed

    private void jbAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarActionPerformed

        try {
            int id = Integer.parseInt(jtfIdTipoHab.getText());
            boolean existe = false;
            TipoHabData th = new TipoHabData();
            TipoHabitacion hb = new TipoHabitacion();

            for (TipoHabitacion tipo : th.listarTipos()) {
                if (id == tipo.getIdTipoHab()) {
                    existe = true;
                    break;
                }
            }

            if (!existe) {

                hb.setIdTipoHab(id);
                hb.setNombre(jtfNombre.getText());
                hb.setCantPersonas(Integer.parseInt(jtfCantPersonas.getText()));
                hb.setCantCamas(Integer.parseInt(jtfCantCamas.getText()));
                hb.setTipoCamas(jtfTipoCama.getText());
                hb.setPrecioxNoche(Double.parseDouble(jtfPrecioxNoche.getText()));
                hb.setEstado(jrbEstado.isSelected());
                th.agregarTipo(hb);
                nuevo();
            } else {
                JOptionPane.showMessageDialog(null, "Ya existe un tipo de habitación con el ID "+id);
            }

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "El Id ingresado debe ser un número");

        }


    }//GEN-LAST:event_jbAgregarActionPerformed

    private void jbNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoActionPerformed
        nuevo();
    }//GEN-LAST:event_jbNuevoActionPerformed

    private void jtfIdTipoHabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfIdTipoHabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfIdTipoHabActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed

        if (jtfBuscar.getText().isEmpty()) {
            System.out.println("Debe ingresar un dato para iniciar la busqueda");
            JOptionPane.showMessageDialog(this, "Debe ingresar un dato para iniciar la busqueda");
        } else {
            TipoHabitacion tipoHab = new TipoHabitacion();
            TipoHabData thd = new TipoHabData();
            try {

                if (thd.obtenerTipoxId(Integer.parseInt(jtfBuscar.getText())) == null) {

                    if (thd.obtenerTipoXPrecio(Double.parseDouble(jtfBuscar.getText())) != null) {
                        tipoHab = thd.obtenerTipoXPrecio(Double.parseDouble(jtfBuscar.getText()));
                        JOptionPane.showMessageDialog(this, "Se ha encontrado una coincidencia en 'precio ' con su busqueda! ");
                    }
                } else {
                    tipoHab = thd.obtenerTipoxId(Integer.parseInt(jtfBuscar.getText()));
                    JOptionPane.showMessageDialog(this, "Se ha encontrado una coincidencia  en ' nro ID Tipo Habitación  o Cantidad de camas' con su busqueda!  ");
                }
            } catch (NumberFormatException nf) {
//                    tipoHab= thd.obtenerTipoXtipoCamas(tipoHab2); // ver xq no funca :'(
            }
            if (tipoHab != null) { // ver porque si no existe busqueda lo llena igual ..... quemadisimaaa!! :S
                jtfIdTipoHab.setText(tipoHab.getIdTipoHab() + "");
//                jtfIdHabitacion.setText(String.valueOf(hab.getIdHabitacion()));
                jtfNombre.setText(tipoHab.getNombre());
                jtfCantPersonas.setText(String.valueOf(tipoHab.getCantPersonas()));
                jtfCantCamas.setText(String.valueOf(tipoHab.getCantCamas()));
                jtfTipoCama.setText(tipoHab.getTipoCamas());
                jtfPrecioxNoche.setText(String.valueOf(tipoHab.getPrecioxNoche()));
                jrbEstado.setSelected(tipoHab.isEstado());

                jtfCantPersonas.setEditable(true);
                jtfCantCamas.setEditable(true);
                jtfTipoCama.setEditable(true);
                jtfPrecioxNoche.setEditable(true);
                jrbEstado.setEnabled(false);
                jtfIdTipoHab.setEditable(false);
            }
        }


    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jtfTipoCamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfTipoCamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfTipoCamaActionPerformed

    private void jtfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNombreActionPerformed

    private void jrbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbEstadoActionPerformed

    private void jbDarAltaBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDarAltaBajaActionPerformed
        TipoHabData thd = new TipoHabData();
        TipoHabitacion th = thd.obtenerTipoxId(Integer.parseInt(jtfIdTipoHab.getText()));

        if (th.isEstado()) {

            int opcion = JOptionPane.showConfirmDialog(null, "El tipo habitación con id:" + jtfIdTipoHab.getText() + " se dará de baja, está seguro? ", " confirmar alta ", JOptionPane.YES_NO_CANCEL_OPTION);
            switch (opcion) {

                case JOptionPane.YES_OPTION:
                    thd.darDeBajaTipo(th);
                    jrbEstado.setSelected(false);
                    jrbEstado.setEnabled(false);
                    JOptionPane.showMessageDialog(null, "Se ha dado de baja exitosamente.");
                    break;
                case JOptionPane.NO_OPTION:
                    if (th.isEstado()) {
                        jrbEstado.setSelected(true);
                    } else {
                        jrbEstado.setSelected(false);
                    }
                    JOptionPane.showMessageDialog(null, "No se ha modificado su estado.");
                    break;
                case JOptionPane.CANCEL_OPTION:
                    JOptionPane.showMessageDialog(null, "Ud. ha cancelado la operación.");
                    break;
            }

        } else {
            int opcion = JOptionPane.showConfirmDialog(null, "El tipo habitación con id:" + jtfIdTipoHab.getText() + " se dará de alta, está seguro? ", " confirmar alta ", JOptionPane.YES_NO_CANCEL_OPTION);
            switch (opcion) {

                case JOptionPane.YES_OPTION:
                    thd.darDeAltaTipo(th);
                    jrbEstado.setSelected(true);
                    jrbEstado.setEnabled(false);
                    JOptionPane.showMessageDialog(null, "Se ha dado de alta exitosamente.");
                    break;
                case JOptionPane.NO_OPTION:
                    JOptionPane.showMessageDialog(null, "No se ha modificado su estado.");
                    break;
                case JOptionPane.CANCEL_OPTION:
                    JOptionPane.showMessageDialog(null, "Ud ha cancelado la operación.");
                    break;
            }

        }
    }//GEN-LAST:event_jbDarAltaBajaActionPerformed

    private void jtfBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfBuscarActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jbSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbAgregar;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbDarAltaBaja;
    private javax.swing.JButton jbModificar;
    private javax.swing.JButton jbNuevo;
    private javax.swing.JButton jbSalir;
    private javax.swing.JLabel jlTipoCama;
    private javax.swing.JRadioButton jrbEstado;
    private javax.swing.JTextField jtfBuscar;
    private javax.swing.JTextField jtfCantCamas;
    private javax.swing.JTextField jtfCantPersonas;
    private javax.swing.JTextField jtfIdTipoHab;
    private javax.swing.JTextField jtfNombre;
    private javax.swing.JTextField jtfPrecioxNoche;
    private javax.swing.JTextField jtfTipoCama;
    // End of variables declaration//GEN-END:variables
public static void llenarCamposTipoHabitacion(TipoHabitacion th, Habitacion hab, JTextField jtfIdTipoHab, JTextField jtfIdHabitacion, JTextField jtfNombre, JTextField jtfCantPersonas, JTextField jtfCantCamas, JTextField jtfTipoCama, JTextField jtfPrecioxNoche) {

        try {
            if (th != null) {
                jtfIdHabitacion.setText(String.valueOf(hab.getIdHabitacion()));
                jtfNombre.setText(th.getNombre());
                jtfCantPersonas.setText(String.valueOf(th.getCantPersonas()));
                jtfCantCamas.setText(String.valueOf(th.getCantCamas()));
                jtfTipoCama.setText(th.getTipoCamas());
                jtfPrecioxNoche.setText(String.valueOf(th.getPrecioxNoche()));
                jtfIdTipoHab.setEditable(false);
                jtfCantPersonas.setEditable(false);
                jtfCantCamas.setEditable(false);
                jtfTipoCama.setEditable(false);
                jtfPrecioxNoche.setEditable(false);
                jtfIdHabitacion.setEditable(false);
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "*Error dato mal ingresado!*");
        }
    }

    private void nuevo() {
        jtfIdTipoHab.setText("");
        jtfNombre.setText("");
        jtfCantCamas.setText("");
        jtfCantPersonas.setText("");
        jtfPrecioxNoche.setText("");
        jtfTipoCama.setText("");
        jrbEstado.setSelected(false);
        jtfBuscar.setText("");
        jtfIdTipoHab.setEditable(true);
        jtfCantCamas.setEditable(true);
        jtfCantPersonas.setEditable(true);
        jtfPrecioxNoche.setEditable(true);
        jtfTipoCama.setEditable(true);
        jrbEstado.setEnabled(true);
        jtfBuscar.setEditable(true);
    }
}
