/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import accesoADatos.ReservaData;
import entidades.Huesped;
import entidades.Personal;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.beans.PropertyVetoException;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author SANTIAGONB
 */
public class VistaPrincipal extends javax.swing.JFrame {

    public static boolean login = false;
    public static boolean personal = false;
    public static Personal personalActivo = null;
    public static Huesped huespedActivo = null;
    public static ArrayList<javax.swing.JDesktopPane> escritorios = new ArrayList<>();
    public static ArrayList<javax.swing.JFrame> vistaP = new ArrayList<>();

    public VistaPrincipal() {
        
        initComponents();
        //this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        escritorios.add(jEscritorio);
        vistaP.add(this);
        repaint();
        new ReservaData().actualizarDisponibilidad();
        mostrarVista(new ReservarHabitacion());
        

        // COMENTARIO DE PRUEBA
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon fondoIcon = new ImageIcon(getClass().getResource("/imagenes/fondo.jpg"));
        Image fondoImagen = fondoIcon.getImage();
        jEscritorio = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(fondoImagen,0,0,getWidth(),getHeight(),this);
            }
        };
        jBarraMenu = new javax.swing.JMenuBar();
        jMenuLogin = new javax.swing.JMenu();
        jMenuLoginH = new javax.swing.JMenuItem();
        jMenuLoginP = new javax.swing.JMenuItem();
        jMenuCerrarSesion = new javax.swing.JMenuItem();
        jMenuHuespedes = new javax.swing.JMenu();
        jMenuManejoHu = new javax.swing.JMenuItem();
        jMenuHabitaciones = new javax.swing.JMenu();
        jMenuManejoHab = new javax.swing.JMenuItem();
        jMenuTiposHab = new javax.swing.JMenuItem();
        jMenuReservas = new javax.swing.JMenu();
        jMenuReservarHab = new javax.swing.JMenuItem();
        jMenuAmpliarRes = new javax.swing.JMenuItem();
        jMenuAbanonarHab = new javax.swing.JMenuItem();
        jMenuConsultas = new javax.swing.JMenu();
        jMenuHuActuales = new javax.swing.JMenuItem();
        jMenuDispHab = new javax.swing.JMenuItem();
        jMenuResActuales = new javax.swing.JMenuItem();
        jMenuPersonal = new javax.swing.JMenu();
        jMenuManejoPersonal = new javax.swing.JMenuItem();
        jGaleria1 = new javax.swing.JMenu();
        jMenuSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hotel California: Sistema de gestión para hotelería");
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/hc_logo.png")).getImage());
        setMinimumSize(new java.awt.Dimension(700, 400));

        jEscritorio.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout jEscritorioLayout = new javax.swing.GroupLayout(jEscritorio);
        jEscritorio.setLayout(jEscritorioLayout);
        jEscritorioLayout.setHorizontalGroup(
            jEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1100, Short.MAX_VALUE)
        );
        jEscritorioLayout.setVerticalGroup(
            jEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 577, Short.MAX_VALUE)
        );

        jMenuLogin.setText("Login");
        jMenuLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuLoginMouseClicked(evt);
            }
        });
        jMenuLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLoginActionPerformed(evt);
            }
        });

        jMenuLoginH.setText("Ingreso para  huéspedes");
        jMenuLoginH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLoginHActionPerformed(evt);
            }
        });
        jMenuLogin.add(jMenuLoginH);

        jMenuLoginP.setText("Ingreso para personal");
        jMenuLoginP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLoginPActionPerformed(evt);
            }
        });
        jMenuLogin.add(jMenuLoginP);

        jMenuCerrarSesion.setText("Cerrar sesión");
        jMenuCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCerrarSesionActionPerformed(evt);
            }
        });
        jMenuLogin.add(jMenuCerrarSesion);

        jBarraMenu.add(jMenuLogin);

        jMenuHuespedes.setText("Huespedes");
        jMenuHuespedes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuHuespedesActionPerformed(evt);
            }
        });

        jMenuManejoHu.setText("Manejo de huéspedes");
        jMenuManejoHu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuManejoHuActionPerformed(evt);
            }
        });
        jMenuHuespedes.add(jMenuManejoHu);

        jBarraMenu.add(jMenuHuespedes);

        jMenuHabitaciones.setText("Habitaciones");

        jMenuManejoHab.setText("Manejo de habitaciones");
        jMenuManejoHab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuManejoHabMouseClicked(evt);
            }
        });
        jMenuManejoHab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuManejoHabActionPerformed(evt);
            }
        });
        jMenuHabitaciones.add(jMenuManejoHab);

        jMenuTiposHab.setText("Tipos de habitaciones");
        jMenuTiposHab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuTiposHabActionPerformed(evt);
            }
        });
        jMenuHabitaciones.add(jMenuTiposHab);

        jBarraMenu.add(jMenuHabitaciones);

        jMenuReservas.setText("Reservas");
        jMenuReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuReservasActionPerformed(evt);
            }
        });

        jMenuReservarHab.setText("Reservar habitación");
        jMenuReservarHab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuReservarHabActionPerformed(evt);
            }
        });
        jMenuReservas.add(jMenuReservarHab);

        jMenuAmpliarRes.setText("Ampliar reserva");
        jMenuAmpliarRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAmpliarResActionPerformed(evt);
            }
        });
        jMenuReservas.add(jMenuAmpliarRes);

        jMenuAbanonarHab.setText("Abandonar habitación");
        jMenuAbanonarHab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAbanonarHabActionPerformed(evt);
            }
        });
        jMenuReservas.add(jMenuAbanonarHab);

        jBarraMenu.add(jMenuReservas);

        jMenuConsultas.setText("Consultas");

        jMenuHuActuales.setText("Huespedes actuales");
        jMenuHuActuales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuHuActualesActionPerformed(evt);
            }
        });
        jMenuConsultas.add(jMenuHuActuales);

        jMenuDispHab.setText("Disponibilidad de habitaciones");
        jMenuDispHab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuDispHabActionPerformed(evt);
            }
        });
        jMenuConsultas.add(jMenuDispHab);

        jMenuResActuales.setText("Reservas actuales");
        jMenuResActuales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuResActualesActionPerformed(evt);
            }
        });
        jMenuConsultas.add(jMenuResActuales);

        jBarraMenu.add(jMenuConsultas);

        jMenuPersonal.setText("Personal");

        jMenuManejoPersonal.setText("Manejo de Personal");
        jMenuManejoPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuManejoPersonalActionPerformed(evt);
            }
        });
        jMenuPersonal.add(jMenuManejoPersonal);

        jBarraMenu.add(jMenuPersonal);

        jGaleria1.setText("Galeria");
        jGaleria1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jGaleria1MouseClicked(evt);
            }
        });
        jGaleria1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGaleria1ActionPerformed(evt);
            }
        });
        jBarraMenu.add(jGaleria1);

        jMenuSalir.setText("Salir");
        jMenuSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSalirMouseClicked(evt);
            }
        });
        jMenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSalirActionPerformed(evt);
            }
        });
        jBarraMenu.add(jMenuSalir);

        setJMenuBar(jBarraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jEscritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jEscritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSalirActionPerformed

    }//GEN-LAST:event_jMenuSalirActionPerformed

    private void jMenuSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jMenuSalirMouseClicked

    private void jMenuLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuLoginMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuLoginMouseClicked

    private void jMenuLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuLoginActionPerformed

    private void jMenuLoginHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLoginHActionPerformed
        personal = false;
        mostrarVista(new Login(personal));
    }//GEN-LAST:event_jMenuLoginHActionPerformed

    private void jMenuLoginPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLoginPActionPerformed
        personal = true;
        mostrarVista(new Login(personal));
    }//GEN-LAST:event_jMenuLoginPActionPerformed

    private void jMenuManejoHuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuManejoHuActionPerformed
        ManejoDeHuespedes manejoHue = new ManejoDeHuespedes();
        mostrarVista(manejoHue);
    }//GEN-LAST:event_jMenuManejoHuActionPerformed

    private void jMenuHuespedesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuHuespedesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuHuespedesActionPerformed

    private void jMenuManejoHabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuManejoHabMouseClicked

    }//GEN-LAST:event_jMenuManejoHabMouseClicked

    private void jMenuManejoHabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuManejoHabActionPerformed
        ManejodeHabitaciones manejoH = new ManejodeHabitaciones();
        mostrarVista(manejoH);

    }//GEN-LAST:event_jMenuManejoHabActionPerformed

    private void jMenuTiposHabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuTiposHabActionPerformed
        TipoHabitaciones tipoHabVista = new TipoHabitaciones();
        mostrarVista(tipoHabVista);
    }//GEN-LAST:event_jMenuTiposHabActionPerformed

    private void jMenuDispHabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuDispHabActionPerformed
        DispoHabitaciones dispoHabs = new DispoHabitaciones();
        mostrarVista(dispoHabs);
    }//GEN-LAST:event_jMenuDispHabActionPerformed

    private void jMenuReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuReservasActionPerformed

    }//GEN-LAST:event_jMenuReservasActionPerformed

    private void jMenuAbanonarHabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAbanonarHabActionPerformed
        mostrarVista(new CancelarReserva());
    }//GEN-LAST:event_jMenuAbanonarHabActionPerformed

    private void jMenuReservarHabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuReservarHabActionPerformed
        mostrarVista(new ReservarHabitacion());
    }//GEN-LAST:event_jMenuReservarHabActionPerformed

    private void jMenuManejoPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuManejoPersonalActionPerformed
        mostrarVista(new ManejoDePersonal());
    }//GEN-LAST:event_jMenuManejoPersonalActionPerformed

    private void jMenuCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCerrarSesionActionPerformed
        login = false;
        personal = false;
        personalActivo = null;
        huespedActivo = null;
        this.repaint();
        mostrarVista(new ReservarHabitacion());
    }//GEN-LAST:event_jMenuCerrarSesionActionPerformed


    private void jMenuHuActualesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuHuActualesActionPerformed
        HuespedesActuales hActual = new HuespedesActuales();
        mostrarVista(hActual);
    }//GEN-LAST:event_jMenuHuActualesActionPerformed

    private void jMenuAmpliarResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAmpliarResActionPerformed
        mostrarVista(new AmpliarReserva());
        //comentario
    }//GEN-LAST:event_jMenuAmpliarResActionPerformed

    private void jMenuResActualesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuResActualesActionPerformed
        ReservasActuales ra= new ReservasActuales();
        mostrarVista(ra);
    }//GEN-LAST:event_jMenuResActualesActionPerformed

    private void jGaleria1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGaleria1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jGaleria1ActionPerformed

    private void jGaleria1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jGaleria1MouseClicked
        mostrarVista(new Galeria());
    }//GEN-LAST:event_jGaleria1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jBarraMenu;
    private javax.swing.JDesktopPane jEscritorio;
    private javax.swing.JMenu jGaleria1;
    private javax.swing.JMenuItem jMenuAbanonarHab;
    private javax.swing.JMenuItem jMenuAmpliarRes;
    private javax.swing.JMenuItem jMenuCerrarSesion;
    private javax.swing.JMenu jMenuConsultas;
    private javax.swing.JMenuItem jMenuDispHab;
    private javax.swing.JMenu jMenuHabitaciones;
    private javax.swing.JMenuItem jMenuHuActuales;
    private javax.swing.JMenu jMenuHuespedes;
    private javax.swing.JMenu jMenuLogin;
    private javax.swing.JMenuItem jMenuLoginH;
    private javax.swing.JMenuItem jMenuLoginP;
    private javax.swing.JMenuItem jMenuManejoHab;
    private javax.swing.JMenuItem jMenuManejoHu;
    private javax.swing.JMenuItem jMenuManejoPersonal;
    private javax.swing.JMenu jMenuPersonal;
    private javax.swing.JMenuItem jMenuResActuales;
    private javax.swing.JMenuItem jMenuReservarHab;
    private javax.swing.JMenu jMenuReservas;
    private javax.swing.JMenu jMenuSalir;
    private javax.swing.JMenuItem jMenuTiposHab;
    // End of variables declaration//GEN-END:variables

    public static void mostrarVista(JInternalFrame vista) {
        escritorios.get(0).removeAll();
        escritorios.get(0).repaint();
        vista.setVisible(true);
        escritorios.get(0).add(vista);
        Dimension desktopSize = escritorios.get(0).getSize();
        Dimension frameSize = vista.getSize();
        escritorios.get(0).moveToFront(vista);
        vista.setLocation((desktopSize.width - frameSize.width) / 2, (desktopSize.height - frameSize.height) / 2);
        try {
            vista.setSelected(true);
        } catch (PropertyVetoException ex) {
            JOptionPane.showMessageDialog(null, "Error de ventana interna");
        }
    }

    @Override
    public void repaint() {
        super.repaint();
        if (!personal) {
            jMenuHabitaciones.setVisible(false);
            jMenuConsultas.setVisible(false);
            jMenuHabitaciones.setVisible(false);
            jMenuHuespedes.setVisible(false);
            jMenuReservas.setVisible(false);
            jMenuPersonal.setVisible(false);
            if (huespedActivo != null) {
                jMenuHuespedes.setVisible(true);
                jMenuReservas.setVisible(true);
            }
        } else {
            jMenuHabitaciones.setVisible(true);
            jMenuConsultas.setVisible(true);
            jMenuHabitaciones.setVisible(true);
            jMenuHuespedes.setVisible(true);
            jMenuReservas.setVisible(true);
            jMenuPersonal.setVisible(true);
        }
    }


}
